/* DOM interaction test; deliberately not a browser/layout/media playback test. */
const {parseHTML}=require('../.build-cache/ui-tests/node_modules/linkedom');
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../dist'),{window}=parseHTML(fs.readFileSync(path.join(root,'index.html'),'utf8'));
const source={path:'/synthetic/master.mp4',sampleHash:'abc'};
const clip={id:'clip1',revision:1,title:'Prueba',source,duration:60,blocks:[{uid:'a',start:1,end:5,text:'Hola mundo'}],status:'draft',format:{aspect:'original',mode:'contain',x:.5,y:.5}};
const clip2={...clip,id:'clip2',title:'Otro tramo del mismo máster',blocks:[{uid:'b',start:20,end:25,text:'Otro tramo'}]};
let workspace={fragments:[],positions:{},view:'grid',visual:null},jobs=[],listeners={},failUpdate=false,libraryAfterImport=null;
Object.assign(window,{console,setTimeout,clearTimeout,setInterval,clearInterval,URL,alert:()=>{},confirm:()=>false,scrollTo:()=>{},requestAnimationFrame:fn=>setTimeout(fn,0),localStorage:{getItem:()=>null,setItem:()=>{}},getComputedStyle:()=>({flexDirection:'row',paddingLeft:'0',paddingRight:'0'})});
Object.defineProperties(window.HTMLElement.prototype,{clientWidth:{get:()=>1000},clientHeight:{get:()=>600}});
window.HTMLElement.prototype.getBoundingClientRect=()=>({width:1000,height:600,left:0,right:1000,top:0,bottom:600});
window.HTMLElement.prototype.scrollIntoView=()=>{};
window.HTMLElement.prototype.pause=()=>{};
window.HTMLElement.prototype.load=()=>{};
window.HTMLElement.prototype.play=async()=>{};
for(const video of window.document.querySelectorAll('video')){video.pause=()=>{};video.load=()=>{};video.play=async()=>{};video.currentTime=0;video.paused=true;}
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){return this._value||this.querySelector('option[selected]')?.getAttribute('value')||this.querySelector('option')?.getAttribute('value')||'';},set(v){this._value=v;}});
window.__TAURI__={core:{convertFileSrc:p=>'asset://'+p,invoke:async(name,args)=>{
  if(name==='list_projects')return [];
  if(name==='update_project'){if(failUpdate)throw Error('No se pudo guardar el proyecto');return {id:args.id,path:'/project/one',name:'Uno',settings:args.settings};}
  if(name==='start_stage1_job'){jobs.push(args.request);return {};}
  if(name==='stage1_query'){const r=args.request;
    if(['library','library_snapshot'].includes(r.op))return {clips:libraryAfterImport||(r.projectPath==='/project/one'?[clip,clip2]:[]),assets:[],draft:null};
    if(r.op==='studio_load')return workspace;
    if(r.op==='studio_save'){workspace=r.workspace;return workspace;}
    if(r.op==='studio_visual')return {samples:[{time:2,faces:[],bodies:[],text:[]}]};
    if(r.op==='source')return {source,media:{duration:60,width:1920,height:1080},words:[{text:'Hola',start:1,end:2},{text:'mundo',start:2,end:3}]};
    if(r.op==='draft')return {};
  }
  return {};
}},dialog:{open:async()=>null},event:{listen:async(name,fn)=>{(listeners[name]??=[]).push(fn);return ()=>{};}}};
const ctx=vm.createContext(window);
for(const file of ['activity.js','app.js','stage1-core.js','vendor/split.js','vendor/icons.js','floating-preview.js','stage1.js','ux.js','hotfix.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});
const tick=()=>new Promise(r=>setTimeout(r,15));
 window.AbrxsBatch={plan:async()=>({exportAfterImport:true,cutMethod:'preferred'})};
(async()=>{
  await tick();
  assert.equal(window.document.querySelectorAll('.ux-sidebar').length,1);
  assert.equal(window.document.querySelectorAll('.ux-sidebar svg').length,4);
  assert.equal(window.document.getElementById('ac-studio').parentElement.className,'shell');
  await vm.runInContext("openProject({id:'one',path:'/project/one',name:'Uno',settings:{video:'/synthetic/master.mp4'}})",ctx);await tick();
  assert.equal(window.document.body.dataset.route,'prepare');
  assert.equal(window.document.getElementById('ux-master-video').hidden,false);
  await window.AbrxsStudio.review();await tick();
  assert.equal(window.document.body.dataset.route,'review');
  assert.ok(window.document.querySelector('[data-edit="clip1"]'));
  await window.document.querySelector('[data-review="clip1"]').onclick();
  assert.equal(window.document.body.dataset.route,'review');
  assert.equal(window.document.querySelector('.ac-library-preview').hidden,false);
  assert.equal(window.document.getElementById('ac-library-title').textContent,'Prueba');
  assert.equal(window.document.getElementById('ac-editor').hidden,true);
  const preview=window.document.getElementById('ac-library-video');preview.readyState=1;preview.currentTime=39;
  await window.document.querySelector('[data-review="clip1"]').onclick();assert.equal(preview.currentTime,1,'Same master must restart without loadedmetadata');
  await window.document.querySelector('[data-review="clip2"]').onclick();assert.equal(preview.currentTime,20,'Each clip must seek its own source start');
  await window.document.querySelector('[data-review="clip1"]').onclick();assert.equal(preview.currentTime,1,'Returning to a clip must reset again');
  await window.document.querySelector('[data-view="map"]').onclick();assert.equal(window.document.querySelector('.ac-library-preview').classList.contains('is-floating'),true);assert.equal(window.document.querySelector('.ac-library-layout').classList.contains('with-preview'),false);
  const viewerButton=text=>[...window.document.querySelectorAll('.ac-viewer-header button')].find(b=>b.textContent===text);
  viewerButton('Plegar').onclick();assert.equal(window.document.querySelector('.ac-viewer-body').hidden,true);viewerButton('Desplegar').onclick();viewerButton('Cerrar').onclick();assert.equal(window.document.querySelector('.ac-library-preview').hidden,true);
  window.document.getElementById('ac-show-viewer').onclick();assert.equal(window.document.querySelector('.ac-library-preview').hidden,false);
  await window.document.querySelector('[data-view="list"]').onclick();assert.equal(window.document.querySelector('.ac-library-layout').classList.contains('with-preview'),true);
  let confirmations=0;window.__TAURI__.dialog.confirm=async()=>{confirmations++;return false;};
  await window.document.getElementById('ac-cache').onclick();assert.equal(confirmations,1);
  await window.document.querySelector('[data-edit="clip1"]').onclick();await tick();
  assert.equal(window.document.getElementById('ac-montage-mode').getAttribute('aria-pressed'),'true');
  assert.equal(window.document.getElementById('ac-inspector').nextElementSibling.id,'ac-blocks');
  assert.equal(window.document.querySelector('.ac-precision').hasAttribute('open'),false);
  window.document.getElementById('ac-origin-mode').onclick();
  await window.AbrxsStudio.create();await tick();
  assert.equal(window.document.getElementById('ac-montage-mode').getAttribute('aria-pressed'),'true');
  assert.equal(window.document.body.dataset.route,'create');
  assert.equal(window.document.querySelectorAll('.gutter').length,2);
  await window.AbrxsStudio.leave();await tick();
  assert.equal(window.document.querySelectorAll('.gutter').length,0);
  await vm.runInContext("openProject({id:'two',path:'/project/two',name:'Dos',settings:{}})",ctx);await tick();
  assert.equal(window.document.getElementById('ux-master-video').hidden,true);
  assert.equal(window.document.querySelector('[data-edit="clip1"]'),null);
  vm.runInContext("setPath('video','/synthetic/two.mp4',false)",ctx);
  await window.AbrxsStudio.prepare('visual');await tick();
  assert.equal(window.document.body.dataset.route,'prepare');
  assert.equal(jobs.length,1);
  assert.equal(window.document.getElementById('ac-progress').hidden,false);
  assert.equal(window.document.getElementById('ac-progress').parentElement.className,'ux-feedback');
  assert.equal(window.document.getElementById('startBtn').disabled,true);
  await vm.runInContext('startJob()',ctx);
  assert.equal(jobs.length,1);
  assert.ok(window.document.getElementById('activityText').textContent.includes('Preparación en curso'));
  const emit=async(name,payload)=>{for(const fn of listeners[name]||[])await fn({payload});};
  await emit('stage1-event',{event:'result',requestId:jobs[0].requestId,data:{path:'/analysis.json',textPath:'/analysis.txt',samples:[],lost:0}});
  await emit('stage1-event',{event:'finished',requestId:jobs[0].requestId,success:true});
  assert.equal(workspace.visual,'/analysis.json');
  assert.ok(!window.document.getElementById('ac-message').textContent.includes('blocks'));
  assert.equal(window.AbrxsStudio.busy,false);
  await window.document.getElementById('ux-refresh-evidence').onclick();await tick();
  assert.equal(window.document.querySelectorAll('#ux-evidence button').length,1);
  const master=window.document.getElementById('ux-master-video');let stopped=false;master.pause=()=>{stopped=true;};
  window.document.querySelector('#ux-evidence button').onclick();stopped=false;master.currentTime=7;master.dispatchEvent(new window.Event('timeupdate'));
  assert.equal(stopped,true);
  failUpdate=true;await vm.runInContext('startJob()',ctx);failUpdate=false;
  assert.equal(vm.runInContext('state.running',ctx),false);
  assert.ok(window.document.getElementById('activityText').textContent.includes('No se pudo guardar'));
  vm.runInContext("setPath('editorial','/synthetic/cuts.txt',false)",ctx);
  assert.equal(window.document.getElementById('editorialField').classList.contains('hidden'),false);
  assert.equal(window.document.getElementById('startLabel').textContent,'Preparar y organizar cortes');
  await vm.runInContext('startJob()',ctx);
  vm.runInContext("state.outputResult='/project/one/master'",ctx);
  await emit('job-finished',{success:true,message:'Preparado'});await tick();await tick();
  assert.equal(jobs.at(-1).op,'import');
  assert.equal(jobs.at(-1).editorial,'/synthetic/cuts.txt');
  const imported=jobs.at(-1);libraryAfterImport=[clip];await emit('stage1-event',{event:'result',requestId:imported.requestId,data:{clips:[clip],targetIds:['clip1']}});
  await emit('stage1-event',{event:'finished',requestId:imported.requestId,success:true});await tick();
  assert.equal(jobs.at(-1).op,'export');assert.deepEqual(Array.from(jobs.at(-1).ids),['clip1']);
  const exportJob=jobs.at(-1);clip.exportState='exported';clip.export={path:'/export/clip1.mp4'};
  await emit('stage1-event',{event:'clip_complete',requestId:exportJob.requestId,id:'clip1',progress:100});await tick();
  assert.ok(window.document.getElementById('ac-cards').textContent.includes('Exportado'));
  await emit('stage1-event',{event:'finished',requestId:exportJob.requestId,success:true});await tick();
  await emit('backend-line','ERROR: prueba de detalle real');
  assert.ok(window.document.getElementById('activityText').textContent.includes('prueba de detalle real'));
  console.log('PASS: routes, Split, isolation, no duplicate jobs, visual without clip, failed project save, cuts pipeline and global error log. DOM only.');
})().catch(e=>{console.error(e);process.exitCode=1;});
